seml:
    executable: setup.py
    name: talnet_bmw_40_aug
    output_dir: seml_logs
    project_root_dir: ..

slurm:
  experiments_per_job: 1
  sbatch_options:
    gres: gpu:1
    mem: 16G
    cpus-per-task: 2
    time: 0-02:00

fixed:
  model:
    model_type: talnet
    model_params:
      num_classes: 6
      sample_rate: 32000
      num_mels: 64
      window_size: 2822
      hop_size: 1103
      fmin: 0
      fmax: 8000
      spec_aug: True

    pretrain: True
    pretrain_paths:
      panns_checkpoint_path: "./pretrained/Wavegram_Logmel_Cnn14_mAP=0.439.pth"
      talnet_checkpoint_path: "./pretrained/TALNet.pt"

  training:
    name: talnet_bmw_40_aug
    num_epochs: 500
    min_epochs: 100
    patience: 30
    print_every: 1
    validate_every: 1
    lr_decay: 1.0

  optimization:
    loss_type: CE
    optimizer_type: Adam
    optimizer_params:
      lr: 0.001
      betas: [0.9, 0.999]
      eps: 0.00000001
      weight_decay: 0.0
      amsgrad: True

  data:
    dataset: bmw
    val_percent: 0.2
    test_percent: 0.2
    batch_size: 64
    sample_rate: 32000
    num_workers: 2
    max_class_samples: 40

  cross_validation:
    n_folds: 5